### ISSUE TITLE
remove unused css via tool

### ISSUE THREAD

**Issue by tejasmanohar** [LanceMatch/LanceMatch#15]
remove unused css via deadweight, uncss, or some other tool based on how the codebase currently stands. comment about the terminal command or process used below so i can do same in future

<u>references</u>
https://github.com/giakki/uncss
https://github.com/aanand/deadweight

just that there are a **LOT** of unused styles here that are making the concatenated css file huge and slowing down the request, render, load time, etc.

**Comment by tejasmanohar** [comment]
include this in a rake task. this won't be in the jekyll build process, just can be run whenever as a separate task

**Comment by mazlix** [comment]
Sure, this will probably actually have to be run before `jekyll build` because jekyll-assets .gzips the .css (or I'd just have to manually re gzip the minified css that has gone through `deadweight`)

**Comment by tejasmanohar** [comment]
@mazlix Yeah, within the `build Rakefile, before `jekyll build` command seems like a good place.
