### ISSUE TITLE
Alignment in meet hackers section off

### ISSUE THREAD

**Issue by tejasmanohar** [LanceMatch/LanceMatch#27]
The alignment in the meet our hackers / uncomparable talent / preview our devs section looks off. Mostly between the profile photos and names underneath seems off. Might just be me though, so this is a request to double check :+1: 

maybe it's that the name + profile photos are too close together?

Post feedback in comments here, and reference any PRs if you resolve this.

**Comment by tejasmanohar** [comment]
also, check that the custom fonts are still in tact?

**Comment by mazlix** [comment]
#34 fixes alignment in IMGs, all the image styling issues were because uncss saw `{% image ____ %}` from jekyll-assets rather than an `<img>` tag. So we need to use `<img src="{% asset_path %}" />` now.
