### ISSUE TITLE
cloudfront_distribution_id ENV?

### ISSUE THREAD

**Issue by tejasmanohar** [LanceMatch/LanceMatch#32]
https://github.com/LanceMatch/LanceMatch/blob/master/s3_website.yml#L28

should cloudfront_distribution_id be set in an ENV var instead of hard-coded? what does this id give you access to or is it publicly available information (if not, we need to regenerate it ASAP0. in what cases would this change?

**Comment by mazlix** [comment]
I don't think that it's something you really need to keep private (like the AWS_secret), but it is the kind of thing you might as well put in an .ENV variable. I'll regenerate one anyway, although I'm quite sure there's nothing malicious someone can do with it
