### ISSUE TITLE
Node modules in exclude?

### ISSUE THREAD

**Issue by tejasmanohar** [LanceMatch/LanceMatch#35]
`exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'Rakefile', 's3_website.yml', 'gulpfile.js', 'package.json']`

Should `node_modules/` be added here?

**Comment by mazlix** [comment]
Sorry my node knowledge << ruby knowledge. But unless you're referencing assets from within node_modules (like some `<script src="../node_modules/less/dist/less.js"></script>` or whatever), then you _should_ add `node_modules` to the exclude.

So If you're just using it for Gulp/uncss then yeah add `node_modules`... I think I used `npm_install g ` so I didn't have that folder in my directory.

**Comment by tejasmanohar** [comment]
yup. oh don't use g for that btw :P
